// ============================================================================
// Demo seed data for "Super Ren Group" CRM.
// Static descriptors only — all FK wiring + randomized analytics happen in
// scripts/seed-demo.mjs. Everything here is clearly sample data (titles all
// start with "DEMO:" and buyer/customer fields are obviously dummy).
// ============================================================================

export const DEMO_EMAIL_DOMAIN = "superren.demo";
export const DEMO_PASSWORD = "DemoPass123!";
export const DEMO_AGENCY = "Super Ren Realty Demo";

// --- Privileged accounts ----------------------------------------------------
export const SUPER_ADMIN = {
  email: `superadmin@${DEMO_EMAIL_DOMAIN}`,
  role: "super_admin",
  full_name: "Super Admin Demo",
};

export const ADMIN = {
  email: `admin@${DEMO_EMAIL_DOMAIN}`,
  role: "admin",
  full_name: "Admin Demo",
};

// --- 8 demo agents ----------------------------------------------------------
// `key` is used to reference agents from listings below.
export const AGENTS = [
  {
    key: "aiman",
    email: `aiman@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Aiman Hakimi",
    slug: "aiman-hakimi",
    ren_number: "REN 12345",
    title: "Senior Real Estate Negotiator",
    phone: "+60123456701",
    whatsapp: "+60123456701",
    focus: "KL City & KLCC",
    service_areas: ["KLCC", "KL City", "Bukit Bintang", "Ampang"],
    specialization: ["project", "rental"],
    bio: "Pakar hartanah kawasan KLCC dan pusat bandar Kuala Lumpur. Fokus kepada projek baharu dan sewaan mewah.",
    photo: "/demo/agents/agent-01.svg",
    facebook_url: "https://facebook.com/demo.aiman",
    instagram_url: "https://instagram.com/demo.aiman",
    tiktok_url: "https://tiktok.com/@demo.aiman",
    website_url: "https://superren.demo/aiman-hakimi",
    telegram_username: "aimanhakimi_demo",
  },
  {
    key: "aisyah",
    email: `aisyah@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Nur Aisyah Rahman",
    slug: "nur-aisyah-rahman",
    ren_number: "REN 23456",
    title: "Real Estate Negotiator",
    phone: "+60123456702",
    whatsapp: "+60123456702",
    focus: "Bangi, Kajang, Semenyih",
    service_areas: ["Bangi", "Kajang", "Semenyih"],
    specialization: ["project", "subsale"],
    bio: "Spesialis projek baharu di Bangi, Kajang dan Semenyih. Banyak pilihan rumah mampu milik untuk keluarga muda.",
    photo: "/demo/agents/agent-02.svg",
    facebook_url: "https://facebook.com/demo.aisyah",
    instagram_url: "https://instagram.com/demo.aisyah",
    tiktok_url: "https://tiktok.com/@demo.aisyah",
    website_url: "https://superren.demo/nur-aisyah-rahman",
    telegram_username: "aisyah_demo",
  },
  {
    key: "daniel",
    email: `daniel@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Daniel Lim",
    slug: "daniel-lim",
    ren_number: "REN 34567",
    title: "Real Estate Negotiator",
    phone: "+60123456703",
    whatsapp: "+60123456703",
    focus: "Petaling Jaya & Subang Jaya",
    service_areas: ["Petaling Jaya", "Subang Jaya", "Damansara"],
    specialization: ["subsale", "commercial"],
    bio: "Khidmat hartanah subsale dan komersial di PJ serta Subang Jaya. Pengalaman luas dalam pelaburan hartanah.",
    photo: "/demo/agents/agent-03.svg",
    facebook_url: "https://facebook.com/demo.daniel",
    instagram_url: "https://instagram.com/demo.daniel",
    tiktok_url: "https://tiktok.com/@demo.daniel",
    website_url: "https://superren.demo/daniel-lim",
    telegram_username: "daniellim_demo",
  },
  {
    key: "siti",
    email: `siti@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Siti Hajar Osman",
    slug: "siti-hajar-osman",
    ren_number: "REN 45678",
    title: "Senior Real Estate Negotiator",
    phone: "+60123456704",
    whatsapp: "+60123456704",
    focus: "Shah Alam & Klang",
    service_areas: ["Shah Alam", "Klang"],
    specialization: ["subsale", "project"],
    bio: "Pakar rumah teres subsale di Shah Alam dan Klang. Kadar tutup jualan tinggi dengan proses pantas.",
    photo: "/demo/agents/agent-04.svg",
    facebook_url: "https://facebook.com/demo.siti",
    instagram_url: "https://instagram.com/demo.siti",
    tiktok_url: "https://tiktok.com/@demo.siti",
    website_url: "https://superren.demo/siti-hajar-osman",
    telegram_username: "sitihajar_demo",
  },
  {
    key: "faris",
    email: `faris@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Faris Iskandar",
    slug: "faris-iskandar",
    ren_number: "REN 56789",
    title: "Real Estate Negotiator",
    phone: "+60123456705",
    whatsapp: "+60123456705",
    focus: "Setapak, Wangsa Maju, Gombak",
    service_areas: ["Setapak", "Wangsa Maju", "Gombak"],
    specialization: ["subsale", "rental"],
    bio: "Khidmat hartanah di Setapak, Wangsa Maju dan Gombak. Banyak unit kondominium harga berpatutan.",
    photo: "/demo/agents/agent-05.svg",
    facebook_url: "https://facebook.com/demo.faris",
    instagram_url: "https://instagram.com/demo.faris",
    tiktok_url: "https://tiktok.com/@demo.faris",
    website_url: "https://superren.demo/faris-iskandar",
    telegram_username: "faris_demo",
  },
  {
    key: "michelle",
    email: `michelle@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Michelle Tan",
    slug: "michelle-tan",
    ren_number: "REN 67890",
    title: "Senior Real Estate Negotiator",
    phone: "+60123456706",
    whatsapp: "+60123456706",
    focus: "Mont Kiara, Desa ParkCity, Kepong",
    service_areas: ["Mont Kiara", "Desa ParkCity", "Kepong"],
    specialization: ["rental", "project"],
    bio: "Spesialis kondominium mewah dan sewaan di Mont Kiara serta Desa ParkCity. Khidmat untuk ekspatriat.",
    photo: "/demo/agents/agent-06.svg",
    facebook_url: "https://facebook.com/demo.michelle",
    instagram_url: "https://instagram.com/demo.michelle",
    tiktok_url: "https://tiktok.com/@demo.michelle",
    website_url: "https://superren.demo/michelle-tan",
    telegram_username: "michelletan_demo",
  },
  {
    key: "harith",
    email: `harith@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Harith Zulkifli",
    slug: "harith-zulkifli",
    ren_number: "REN 78901",
    title: "Real Estate Negotiator",
    phone: "+60123456707",
    whatsapp: "+60123456707",
    focus: "Cyberjaya, Putrajaya, Dengkil",
    service_areas: ["Cyberjaya", "Putrajaya", "Dengkil"],
    specialization: ["rental", "project"],
    bio: "Pakar sewaan studio dan apartmen di Cyberjaya serta Putrajaya. Sesuai untuk pelajar dan profesional muda.",
    photo: "/demo/agents/agent-07.svg",
    facebook_url: "https://facebook.com/demo.harith",
    instagram_url: "https://instagram.com/demo.harith",
    tiktok_url: "https://tiktok.com/@demo.harith",
    website_url: "https://superren.demo/harith-zulkifli",
    telegram_username: "harith_demo",
  },
  {
    key: "kavitha",
    email: `kavitha@${DEMO_EMAIL_DOMAIN}`,
    full_name: "Kavitha Raj",
    slug: "kavitha-raj",
    ren_number: "REN 89012",
    title: "Real Estate Negotiator",
    phone: "+60123456708",
    whatsapp: "+60123456708",
    focus: "Puchong, Seri Kembangan, Bukit Jalil",
    service_areas: ["Puchong", "Seri Kembangan", "Bukit Jalil"],
    specialization: ["subsale", "land"],
    bio: "Khidmat hartanah subsale dan tanah di Puchong, Seri Kembangan dan Bukit Jalil. Nasihat pelaburan percuma.",
    photo: "/demo/agents/agent-08.svg",
    facebook_url: "https://facebook.com/demo.kavitha",
    instagram_url: "https://instagram.com/demo.kavitha",
    tiktok_url: "https://tiktok.com/@demo.kavitha",
    website_url: "https://superren.demo/kavitha-raj",
    telegram_username: "kavitharaj_demo",
  },
];

// --- Listings ---------------------------------------------------------------
// `analytics` tags drive the deliberate dashboard scenarios in seed-demo.mjs:
//   high_share_med_conv | strong_close | high_view_low_conv | fast_conv | low_media
// `outcome` hints the deal/status seeding: sold | rented | cancelled | open
// price is the headline price; for rentals it is the MONTHLY rental (also
// written into listings.price per spec).

const SELLING_POINTS_POOL = [
  "Lokasi strategik dekat pengangkutan awam",
  "Kemudahan lengkap untuk keluarga",
  "Persekitaran selamat dan tenang",
  "Hampir dengan sekolah dan pusat membeli-belah",
  "Nilai pelaburan berpotensi tinggi",
  "Reka bentuk moden dan ruang luas",
  "Pemandangan cantik dari unit",
  "Akses mudah ke lebuh raya utama",
];

export const FACILITIES_POOL = [
  "Swimming Pool",
  "Gymnasium",
  "24-Hour Security",
  "Covered Parking",
  "Children Playground",
  "Multipurpose Hall",
  "Surau",
  "BBQ Area",
];

export const AMENITIES_POOL = [
  "Shopping Mall",
  "Hospital",
  "School",
  "LRT/MRT Station",
  "Bank",
  "Restaurant",
  "Supermarket",
  "Park",
];

function sp(...idx) {
  return idx.map((i) => SELLING_POINTS_POOL[i % SELLING_POINTS_POOL.length]);
}

export const LISTINGS = [
  // ========================= PROJECT (15) =========================
  // -- Bangi/Kajang/Semenyih cluster: high shares, high leads, medium conv (opportunity)
  {
    cat: "project", agent: "aisyah", title: "DEMO: Aurora Heights Residence, Bangi",
    property_type: "condo", area: "Bangi", price: 480000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1050, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "high_share_med_conv",
    selling: sp(0, 1, 2, 3, 4),
  },
  {
    cat: "project", agent: "aisyah", title: "DEMO: Southville Green Residence, Bangi",
    property_type: "apartment", area: "Bangi", price: 395000, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 900, tenure: "leasehold", furnishing: "unfurnished",
    status: "viewing_scheduled", outcome: "open", analytics: "high_share_med_conv",
    selling: sp(0, 1, 3, 5, 6),
  },
  {
    cat: "project", agent: "aisyah", title: "DEMO: Semenyih Garden Heights",
    property_type: "terrace", area: "Semenyih", price: 560000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1600, land_area: 1400, tenure: "freehold", furnishing: "unfurnished",
    status: "booked", outcome: "open", analytics: "high_share_med_conv",
    selling: sp(1, 2, 3, 4, 7),
  },
  {
    cat: "project", agent: "aisyah", title: "DEMO: Kajang Heights Serviced Suites",
    property_type: "condo", area: "Kajang", price: 425000, bedrooms: 2, bathrooms: 2,
    carparks: 1, built_up: 850, tenure: "leasehold", furnishing: "partly_furnished",
    status: "sold", outcome: "sold", analytics: "high_share_med_conv",
    selling: sp(0, 2, 4, 5, 6),
  },
  {
    cat: "project", agent: "aisyah", title: "DEMO: Bangi Avenue Park Residence",
    property_type: "condo", area: "Bangi", price: 510000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1100, tenure: "leasehold", furnishing: "partly_furnished",
    status: "sold", outcome: "sold", analytics: "high_share_med_conv",
    selling: sp(0, 1, 2, 4, 7),
  },
  // -- Other projects spread across agents
  {
    cat: "project", agent: "faris", title: "DEMO: KL Urban Suites, Setapak",
    property_type: "condo", area: "Setapak", price: 620000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1080, tenure: "freehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 2, 3, 5, 6),
  },
  {
    cat: "project", agent: "harith", title: "DEMO: CyberLake Serviced Apartment, Cyberjaya",
    property_type: "apartment", area: "Cyberjaya", price: 450000, bedrooms: 2, bathrooms: 2,
    carparks: 1, built_up: 820, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "fast_conv",
    selling: sp(0, 1, 4, 5, 7),
  },
  {
    cat: "project", agent: "daniel", title: "DEMO: Damansara Metro Residence, Petaling Jaya",
    property_type: "condo", area: "Petaling Jaya", price: 880000, bedrooms: 3, bathrooms: 3,
    carparks: 2, built_up: 1250, tenure: "freehold", furnishing: "partly_furnished",
    status: "viewing_scheduled", outcome: "open", analytics: null,
    selling: sp(0, 1, 2, 5, 6),
  },
  {
    cat: "project", agent: "kavitha", title: "DEMO: Bukit Jalil Parkview Suites",
    property_type: "condo", area: "Bukit Jalil", price: 720000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1150, tenure: "leasehold", furnishing: "partly_furnished",
    status: "booked", outcome: "open", analytics: null,
    selling: sp(1, 2, 3, 4, 6),
  },
  {
    cat: "project", agent: "siti", title: "DEMO: Shah Alam Sentral Residences",
    property_type: "condo", area: "Shah Alam", price: 540000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1090, tenure: "leasehold", furnishing: "unfurnished",
    status: "sold", outcome: "sold", analytics: "strong_close",
    selling: sp(0, 1, 3, 4, 7),
  },
  {
    cat: "project", agent: "faris", title: "DEMO: Cheras City Link Residence",
    property_type: "condo", area: "Cheras", price: 650000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1120, tenure: "freehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 2, 4, 5, 6),
  },
  {
    cat: "project", agent: "harith", title: "DEMO: Putrajaya Lakeview Homes",
    property_type: "terrace", area: "Putrajaya", price: 780000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1900, land_area: 1600, tenure: "leasehold", furnishing: "unfurnished",
    status: "available", outcome: "open", analytics: "fast_conv",
    selling: sp(1, 2, 3, 5, 7),
  },
  {
    cat: "project", agent: "aiman", title: "DEMO: KLCC Skyline Residences",
    property_type: "condo", area: "KLCC", price: 1450000, bedrooms: 3, bathrooms: 3,
    carparks: 2, built_up: 1450, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 4, 5, 6, 7),
  },
  {
    cat: "project", agent: "michelle", title: "DEMO: Mont Kiara Sky Garden Suites",
    property_type: "condo", area: "Mont Kiara", price: 1280000, bedrooms: 3, bathrooms: 3,
    carparks: 2, built_up: 1380, tenure: "freehold", furnishing: "partly_furnished",
    status: "draft", outcome: "open", analytics: null,
    selling: sp(0, 1, 5, 6, 7),
  },
  {
    cat: "project", agent: "kavitha", title: "DEMO: Puchong Prima Residence",
    property_type: "apartment", area: "Puchong", price: 360000, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 880, tenure: "leasehold", furnishing: "unfurnished",
    status: "withdrawn", outcome: "open", analytics: null,
    selling: sp(0, 1, 2, 3, 4),
  },

  // ========================= SUBSALE (15) =========================
  // -- Shah Alam/Klang terrace strength: high close rate, fast days-to-close
  {
    cat: "subsale", agent: "siti", title: "DEMO: Renovated Double Storey Terrace, Shah Alam",
    property_type: "terrace", area: "Shah Alam", price: 720000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1800, land_area: 1540, tenure: "freehold", furnishing: "partly_furnished",
    status: "sold", outcome: "sold", analytics: "strong_close",
    selling: sp(0, 1, 2, 3, 5),
  },
  {
    cat: "subsale", agent: "siti", title: "DEMO: Klang Double Storey Terrace",
    property_type: "terrace", area: "Klang", price: 560000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1650, land_area: 1400, tenure: "leasehold", furnishing: "unfurnished",
    status: "sold", outcome: "sold", analytics: "strong_close",
    selling: sp(0, 1, 3, 4, 7),
  },
  {
    cat: "subsale", agent: "siti", title: "DEMO: Single Storey Terrace, Klang",
    property_type: "terrace", area: "Klang", price: 430000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1300, land_area: 1200, tenure: "leasehold", furnishing: "unfurnished",
    status: "sold", outcome: "sold", analytics: "strong_close",
    selling: sp(1, 2, 3, 4, 5),
  },
  {
    cat: "subsale", agent: "siti", title: "DEMO: Corner Terrace with Extra Land, Shah Alam",
    property_type: "terrace", area: "Shah Alam", price: 850000, bedrooms: 4, bathrooms: 3,
    carparks: 3, built_up: 2100, land_area: 2400, tenure: "freehold", furnishing: "partly_furnished",
    status: "booked", outcome: "open", analytics: "strong_close",
    selling: sp(0, 2, 3, 5, 6),
  },
  // -- Other subsale spread
  {
    cat: "subsale", agent: "faris", title: "DEMO: Freehold Condo Near LRT, Wangsa Maju",
    property_type: "condo", area: "Wangsa Maju", price: 480000, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 1000, tenure: "freehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 3, 4, 5, 6),
  },
  {
    cat: "subsale", agent: "kavitha", title: "DEMO: Corner Lot Terrace, Puchong",
    property_type: "terrace", area: "Puchong", price: 690000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1750, land_area: 1900, tenure: "leasehold", furnishing: "unfurnished",
    status: "sold", outcome: "sold", analytics: null,
    selling: sp(1, 2, 3, 4, 6),
  },
  {
    cat: "subsale", agent: "aisyah", title: "DEMO: Family Home Near MRT, Kajang",
    property_type: "terrace", area: "Kajang", price: 620000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1700, land_area: 1500, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "high_share_med_conv",
    selling: sp(0, 1, 2, 3, 7),
  },
  {
    cat: "subsale", agent: "michelle", title: "DEMO: High Floor Condo, Mont Kiara",
    property_type: "condo", area: "Mont Kiara", price: 1650000, bedrooms: 4, bathrooms: 4,
    carparks: 2, built_up: 1850, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 4, 5, 6, 7),
  },
  {
    cat: "subsale", agent: "aiman", title: "DEMO: Subsale Apartment, Ampang",
    property_type: "apartment", area: "Ampang", price: 380000, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 950, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 1, 3, 4, 5),
  },
  {
    cat: "subsale", agent: "kavitha", title: "DEMO: Semi-D with Large Land, Rawang",
    property_type: "semi_d", area: "Rawang", price: 1150000, bedrooms: 5, bathrooms: 4,
    carparks: 4, built_up: 3200, land_area: 4000, tenure: "freehold", furnishing: "unfurnished",
    status: "viewing_scheduled", outcome: "open", analytics: null,
    selling: sp(2, 3, 4, 5, 6),
  },
  {
    cat: "subsale", agent: "kavitha", title: "DEMO: Townhouse Near School, Seri Kembangan",
    property_type: "terrace", area: "Seri Kembangan", price: 540000, bedrooms: 3, bathrooms: 3,
    carparks: 2, built_up: 1450, land_area: 1100, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: null,
    selling: sp(0, 1, 3, 5, 6),
  },
  {
    cat: "subsale", agent: "aiman", title: "DEMO: Bangsar Condo with City View",
    property_type: "condo", area: "Bangsar", price: 1380000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1320, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 4, 5, 6, 7),
  },
  {
    cat: "subsale", agent: "daniel", title: "DEMO: Double Storey Terrace, Subang Jaya",
    property_type: "terrace", area: "Subang Jaya", price: 980000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 2000, land_area: 1760, tenure: "freehold", furnishing: "partly_furnished",
    status: "sold", outcome: "sold", analytics: null,
    selling: sp(0, 1, 2, 3, 4),
  },
  {
    cat: "subsale", agent: "daniel", title: "DEMO: Condo Unit Near Sunway, Petaling Jaya",
    property_type: "condo", area: "Petaling Jaya", price: 750000, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1150, tenure: "freehold", furnishing: "partly_furnished",
    status: "failed", outcome: "cancelled", analytics: null,
    selling: sp(0, 1, 4, 5, 6),
  },
  {
    cat: "subsale", agent: "faris", title: "DEMO: Renovated Apartment, Gombak",
    property_type: "apartment", area: "Gombak", price: 320000, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 880, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 1, 2, 3, 5),
  },

  // ========================= RENTAL (15) =========================
  // -- Mont Kiara/KLCC: high views, high price, low conversion (weakness/threat)
  {
    cat: "rental", agent: "aiman", title: "DEMO: Fully Furnished Studio, KLCC",
    property_type: "condo", area: "KLCC", price: 3500, bedrooms: 1, bathrooms: 1,
    carparks: 1, built_up: 600, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 4, 5, 6, 7),
  },
  {
    cat: "rental", agent: "aiman", title: "DEMO: Luxury 2-Bedroom for Rent, KLCC",
    property_type: "condo", area: "KLCC", price: 6500, bedrooms: 2, bathrooms: 2,
    carparks: 2, built_up: 1100, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 4, 5, 6, 7),
  },
  {
    cat: "rental", agent: "michelle", title: "DEMO: Condo for Rent, Mont Kiara",
    property_type: "condo", area: "Mont Kiara", price: 5500, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1400, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 1, 4, 5, 6),
  },
  {
    cat: "rental", agent: "michelle", title: "DEMO: Premium Family Condo, Desa ParkCity",
    property_type: "condo", area: "Desa ParkCity", price: 8000, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1800, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "high_view_low_conv",
    selling: sp(0, 1, 5, 6, 7),
  },
  {
    cat: "rental", agent: "michelle", title: "DEMO: Service Apartment, Kepong",
    property_type: "apartment", area: "Kepong", price: 1800, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 950, tenure: "leasehold", furnishing: "partly_furnished",
    status: "rented", outcome: "rented", analytics: null,
    selling: sp(0, 1, 2, 3, 4),
  },
  // -- Cyberjaya/Putrajaya studios: leads fast, high rental conversion (strength)
  {
    cat: "rental", agent: "harith", title: "DEMO: Cyberjaya Studio Near University",
    property_type: "condo", area: "Cyberjaya", price: 1300, bedrooms: 1, bathrooms: 1,
    carparks: 1, built_up: 520, tenure: "freehold", furnishing: "fully_furnished",
    status: "rented", outcome: "rented", analytics: "fast_conv",
    selling: sp(0, 1, 2, 3, 5),
  },
  {
    cat: "rental", agent: "harith", title: "DEMO: Affordable Studio for Rent, Cyberjaya",
    property_type: "apartment", area: "Cyberjaya", price: 1200, bedrooms: 1, bathrooms: 1,
    carparks: 1, built_up: 500, tenure: "freehold", furnishing: "fully_furnished",
    status: "rented", outcome: "rented", analytics: "fast_conv",
    selling: sp(0, 1, 2, 4, 5),
  },
  {
    cat: "rental", agent: "harith", title: "DEMO: Serviced Suite for Rent, Putrajaya",
    property_type: "condo", area: "Putrajaya", price: 1600, bedrooms: 2, bathrooms: 2,
    carparks: 1, built_up: 750, tenure: "leasehold", furnishing: "fully_furnished",
    status: "rented", outcome: "rented", analytics: "fast_conv",
    selling: sp(0, 1, 3, 4, 5),
  },
  {
    cat: "rental", agent: "harith", title: "DEMO: Studio Near MRTCC, Cyberjaya",
    property_type: "condo", area: "Cyberjaya", price: 1400, bedrooms: 1, bathrooms: 1,
    carparks: 1, built_up: 540, tenure: "freehold", furnishing: "fully_furnished",
    status: "available", outcome: "open", analytics: "fast_conv",
    selling: sp(0, 1, 2, 3, 4),
  },
  // -- Others spread
  {
    cat: "rental", agent: "daniel", title: "DEMO: Family Rental Unit, Subang Jaya",
    property_type: "condo", area: "Subang Jaya", price: 2600, bedrooms: 3, bathrooms: 2,
    carparks: 2, built_up: 1150, tenure: "freehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: null,
    selling: sp(0, 1, 2, 3, 6),
  },
  {
    cat: "rental", agent: "faris", title: "DEMO: Affordable Apartment, Setapak",
    property_type: "apartment", area: "Setapak", price: 1400, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 850, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "low_media",
    selling: sp(0, 1, 2, 3, 4),
  },
  {
    cat: "rental", agent: "kavitha", title: "DEMO: Serviced Residence, Bukit Jalil",
    property_type: "condo", area: "Bukit Jalil", price: 2200, bedrooms: 2, bathrooms: 2,
    carparks: 1, built_up: 900, tenure: "leasehold", furnishing: "fully_furnished",
    status: "rented", outcome: "rented", analytics: null,
    selling: sp(0, 1, 4, 5, 6),
  },
  {
    cat: "rental", agent: "siti", title: "DEMO: Terrace House for Rent, Shah Alam",
    property_type: "terrace", area: "Shah Alam", price: 2400, bedrooms: 4, bathrooms: 3,
    carparks: 2, built_up: 1700, land_area: 1540, tenure: "leasehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: "strong_close",
    selling: sp(0, 1, 2, 3, 5),
  },
  {
    cat: "rental", agent: "faris", title: "DEMO: Apartment Near MRT, Cheras",
    property_type: "apartment", area: "Cheras", price: 1700, bedrooms: 3, bathrooms: 2,
    carparks: 1, built_up: 900, tenure: "leasehold", furnishing: "partly_furnished",
    status: "rented", outcome: "rented", analytics: null,
    selling: sp(0, 1, 2, 3, 4),
  },
  {
    cat: "rental", agent: "daniel", title: "DEMO: Office Unit for Rent, Petaling Jaya",
    property_type: "office", area: "Petaling Jaya", price: 4500, bedrooms: 0, bathrooms: 2,
    carparks: 3, built_up: 1600, tenure: "freehold", furnishing: "partly_furnished",
    status: "available", outcome: "open", analytics: null,
    selling: sp(0, 3, 4, 5, 6),
  },
];
